package com.fedpol1.enchantips.config;

public enum ModOption {
    SHOW_REPAIRCOST,
    SHOW_ENCHANTABILITY,
    SHOW_ENCHANTABILITY_WHEN_ENCHANTED,
    SHOW_RARITY,
    SHOW_MODIFIED_ENCHANTMENT_LEVEL,
    SHOW_EXTRA_ENCHANTMENTS,
    SHOW_MODIFIED_LEVEL_FOR_ENCHANTMENT,
    SHOW_PROTECTION_BAR,
    SHOW_ANVIL_ITEM_SWAP_BUTTON,
    HIGHLIGHT_LIMIT,
    SHOW_HIGHLIGHTS_SPECIALLY_ENCHANTED,
    HIGHLIGHTS_RESPECT_HIDEFLAGS,
    HIGHLIGHT_HOTBAR_ALPHA,
    HIGHLIGHT_TRADING_ALPHA,
    UNBREAKABLE_COLOR,
    REPAIRCOST,
    REPAIRCOST_VALUE,
    ENCHANTABILITY,
    ENCHANTABILITY_VALUE,
    RARITY_BRACKET,
    MODIFIED_ENCHANTMENT_LEVEL,
    MODIFIED_ENCHANTMENT_LEVEL_VALUE,
    MODIFIED_LEVEL_FOR_ENCHANTMENT,
    MODIFIED_LEVEL_FOR_ENCHANTMENT_VALUE;
}
